# Navigation Links
#   To link a-generalized-framework-for-quantifying-trust-of-social-media-text-documents homepage widget, specify the URL as a-generalized-framework-for-quantifying-trust-of-social-media-text-documents hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


#[[main]]
#  name = "Posts"
#  url = "#post"
#  weight = 20

#[[main]]
#  name = "Opensource"
#  url = "projects/"
#  weight = 10

[[main]]
  name = "Publications"
  url = "publications/"
  weight = 20

[[main]]
  name = "Patents"
  url = "patents/"
  weight = 30

[[main]]
  name = "Blogs"
  url = "blogs/"
  weight = 40

[[main]]
  name = "Talks"
  url = "talks/"
  weight = 50

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 100


#[[main]]
#  name = "Chill"
#  url = "chill/"
#  weight = 70


# Link to a-generalized-framework-for-quantifying-trust-of-social-media-text-documents PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
